name: Build Plugin Package

on:
  push:
    branches:
      - "**/*"
    tags:
      - "v*"
      - "*@v*"
  pull_request:

jobs:
  build:
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build --build-arg NODE=22 -t mt-plugin-asset-uploader-builder .

      - name: Update version string for this build
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: find . -name config.yaml -print0 | xargs -0 perl -i -pe 's/^(version:\s*\d.*)/$1+build-${{ steps.vars.outputs.sha_short }}/'

      - name: Build plugin package
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app mt-plugin-asset-uploader-builder \
          bash -c 'perl Makefile.PL && make manifest && make build && make dist && make zipdist'

      - name: Upload artifact
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: mt-plugin-AssetUploader-${{ steps.vars.outputs.sha_short }}
          path: |
            *.zip
            *.tar.gz

      - name: Upload package to GitHub Releases
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          draft: true
          files: |
            *.zip
            *.tar.gz
