name: Test

on:
  push:
    branches:
      - "**/*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - working-directory: mt-static/plugins/AssetUploader
        run: npm install
      - working-directory: mt-static/plugins/AssetUploader
        run: npm run check && npm run lint
      - working-directory: mt-static/plugins/AssetUploader
        run: npm run test

  perl:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: movabletype/internal-movabletype
          token: ${{ secrets.FETCH_INTERNAL }}
          ref: develop9
          path: mt
      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/mt:/app \
            -v ${{ github.workspace }}/plugins/AssetUploader:/app/plugins/AssetUploader \
            -w /app \
            ghcr.io/movabletype/movabletype/test:bullseye \
          prove -j4 -PMySQLPool=MT::Test::Env -It/lib plugins/AssetUploader/t
